// 표현: phrase는 화면에 보이는 틀, say는 따라 말할 문장, key는 "내 문장"에서 썼는지 확인할 부분.
// 시험에 "자주 나온다"는 근거는 없다 — 답변 틀의 각 자리를 채우는 데 쓰는 표현이다.
const EXPR = {
  // 말 잇기 표현 — 모든 유형 공통 (common: true)
  'c-stall': {
    name: '막힐 때', about: '"음…" 대신 시간 벌기', common: true,
    items: [
      { id: 'c-think', phrase: 'Well, let me think.', ko: '음, 생각해 볼게요.', slot: '첫 마디가 안 떠오를 때',
        say: 'Well, let me think about that.', key: 'let me think',
        ask: 'What do you usually do on weekends?', example: 'Well, let me think. I usually meet my friends on weekends.' },
      { id: 'c-goodq', phrase: "That's a good question.", ko: '좋은 질문이네요.', slot: '질문을 듣고 답이 바로 안 나올 때',
        say: "That's a good question. I've never really thought about it.", key: 'good question',
        ask: 'What is the best gift you have ever received?', example: "That's a good question. I think the best gift was a watch from my parents." },
      { id: 'c-letmesee', phrase: 'Let me see.', ko: '어디 보자.', slot: '기억이나 날짜·숫자를 떠올릴 때',
        say: 'Let me see. I think it was last summer.', key: 'let me see',
        ask: 'When was the last time you went on a trip?', example: 'Let me see. I think it was last summer. I went to Busan with my friends.' },
    ],
  },
  'c-add': {
    name: '이유 더하기', about: '이유를 하나 더 붙이기', common: true,
    items: [
      { id: 'c-ontop', phrase: 'On top of that, …', ko: '게다가, …', slot: '이유를 하나 더 붙일 때',
        say: "On top of that, it's much cheaper.", key: 'on top of that',
        ask: 'Why do you like shopping online?', example: "It saves a lot of time. On top of that, it's often cheaper." },
      { id: 'c-another', phrase: 'Another reason is that …', ko: '또 다른 이유는 …', slot: '두 번째 이유를 꺼낼 때',
        say: "Another reason is that it's good for my health.", key: 'another reason is',
        ask: 'Why do you like walking?', example: "It helps me relax. Another reason is that it's good for my health." },
      { id: 'c-also', phrase: 'Also, …', ko: '그리고, …', slot: '짧게 하나 덧붙일 때',
        say: 'Also, the staff there are really friendly.', key: 'also',
        ask: 'Why do you like your favorite restaurant?', example: 'The food is great. Also, the staff there are really friendly.' },
    ],
  },
  'c-ex': {
    name: '예시 들기', about: '이유를 예로 받쳐주기', common: true,
    items: [
      { id: 'c-giveex', phrase: 'Let me give you an example.', ko: '예를 하나 들어볼게요.', slot: '이유 뒤, 예시로 넘어가는 신호',
        say: 'Let me give you an example.', key: 'give you an example',
        ask: 'Is it important to learn how to cook?', example: 'Yes, I think so. Let me give you an example. When I lived alone, cooking saved me a lot of money.' },
      { id: 'c-instance', phrase: 'For instance, …', ko: '예를 들어, …', slot: '예시를 바로 들 때',
        say: 'For instance, I often cook pasta at home.', key: 'for instance',
        ask: 'Do you like cooking at home?', example: 'Yes, I do. For instance, I often cook pasta at home on weekends.' },
      { id: 'c-goodex', phrase: 'A good example is …', ko: '좋은 예가 …예요.', slot: '구체적인 대상 하나를 가리킬 때',
        say: 'A good example is my neighborhood library.', key: 'a good example is',
        ask: 'Are there good public places in your area?', example: "Yes, there are. A good example is my neighborhood library. It's quiet and free." },
    ],
  },
  'c-clarify': {
    name: '풀어 말하기', about: '방금 한 말을 쉽게, 구체적으로', common: true,
    items: [
      { id: 'c-mean', phrase: 'What I mean is …', ko: '제 말은 …', slot: '방금 한 말을 쉽게 다시 말할 때',
        say: 'What I mean is, it saves a lot of time.', key: 'what i mean is',
        ask: 'Why do you like online banking?', example: "It's really convenient. What I mean is, it saves a lot of time." },
      { id: 'c-otherwords', phrase: 'In other words, …', ko: '다시 말해, …', slot: '앞 내용을 한 줄로 정리할 때',
        say: "In other words, it's worth the money.", key: 'in other words',
        ask: 'Is a gym membership worth the money?', example: "I go to the gym almost every day. In other words, it's worth the money." },
      { id: 'c-specific', phrase: 'To be more specific, …', ko: '구체적으로 말하면, …', slot: '막연한 답에 시간·장소·횟수를 붙일 때',
        say: 'To be more specific, I go there every Friday night.', key: 'to be more specific',
        ask: 'How often do you eat out?', example: 'I eat out quite often. To be more specific, I go to a restaurant every Friday night.' },
    ],
  },
  'c-contrast': {
    name: '반대·양보', about: '단점이나 다른 쪽 말하기', common: true,
    items: [
      { id: 'c-however', phrase: 'However, …', ko: '하지만, …', slot: '단점이나 반대 사실을 말할 때',
        say: 'However, it can be a little expensive.', key: 'however',
        ask: 'What do you think about taking taxis?', example: 'Taxis are fast and comfortable. However, they can be a little expensive.' },
      { id: 'c-otherhand', phrase: 'On the other hand, …', ko: '반면에, …', slot: '두 가지를 비교할 때',
        say: 'On the other hand, working alone is less stressful.', key: 'on the other hand',
        ask: 'Do you prefer working alone or in a team?', example: 'Working in a team is fun. On the other hand, working alone is less stressful.' },
      { id: 'c-eventhough', phrase: 'Even though …, …', ko: '…이긴 하지만, …', slot: '단점을 인정하고 내 선택을 말할 때',
        say: "Even though it's far, I still go there often.", key: 'even though',
        ask: 'Do you have a favorite place that is far from your home?', example: "Yes. There's a park by the river. Even though it's far, I still go there often." },
    ],
  },
  'c-result': {
    name: '원인·결과', about: '그래서 어떻게 됐는지', common: true,
    items: [
      { id: 'c-thatswhy', phrase: "That's why I …", ko: '그래서 저는 …', slot: '이유를 말한 뒤 답을 다시 묶을 때',
        say: "That's why I prefer to take the subway.", key: "that's why",
        ask: 'Do you prefer taking the bus or the subway?', example: "The subway is never stuck in traffic. That's why I prefer to take the subway." },
      { id: 'c-becauseofthat', phrase: 'Because of that, …', ko: '그 때문에, …', slot: '원인을 말한 뒤 결과를 이을 때',
        say: 'Because of that, I always leave home early.', key: 'because of that',
        ask: 'How is the traffic in your city?', example: 'The traffic is really bad in the morning. Because of that, I always leave home early.' },
      { id: 'c-asresult', phrase: 'As a result, …', ko: '그 결과, …', slot: '경험을 말한 뒤 얻은 것을 말할 때',
        say: 'As a result, I saved a lot of money.', key: 'as a result',
        ask: 'Have you ever changed a habit?', example: 'I stopped buying coffee every day. As a result, I saved a lot of money.' },
    ],
  },
  'c-exp': {
    name: '내 경험 꺼내기', about: '시간 채우기, 특히 11번', common: true,
    items: [
      { id: 'c-mycase', phrase: 'In my case, …', ko: '제 경우에는, …', slot: '일반론 대신 내 이야기로 시작할 때',
        say: 'In my case, I usually study at a cafe.', key: 'in my case',
        ask: 'Where do people usually study?', example: 'Many people study at home. In my case, I usually study at a cafe.' },
      { id: 'c-college', phrase: 'When I was in college, …', ko: '대학생 때, …', slot: '예시로 과거 경험을 꺼낼 때',
        tip: '대학 경험이 없으면 When I was in high school 처럼 바꿔 쓰세요.',
        say: 'When I was in college, I worked part-time at a bookstore.', key: 'when i was',
        ask: 'Have you ever had a part-time job?', example: 'Yes. When I was in college, I worked part-time at a bookstore.' },
      { id: 'c-remember', phrase: 'I remember when …', ko: '…했던 때가 기억나요.', slot: '짧은 이야기로 시간을 채울 때',
        say: 'I remember when I first moved to Seoul.', key: 'i remember when',
        ask: 'Have you ever felt lost in a new place?', example: 'Yes. I remember when I first moved to Seoul. Everything felt so big.' },
    ],
  },
  'c-close': {
    name: '마무리', about: '답을 한 문장으로 묶기', common: true,
    items: [
      { id: 'c-overall', phrase: 'So overall, …', ko: '그래서 전체적으로, …', slot: '답변을 한 문장으로 정리할 때',
        say: "So overall, I think it's a great idea.", key: 'overall',
        ask: 'Is it a good idea to learn a new language?', example: "It can give you more job chances. So overall, I think it's a great idea." },
      { id: 'c-mainreason', phrase: "That's the main reason why …", ko: '그게 …하는 가장 큰 이유예요.', slot: '이유를 말한 뒤 답으로 돌아갈 때',
        say: "That's the main reason why I like it.", key: 'the main reason why',
        ask: 'Why do you like your hometown?', example: "My family and friends live there. That's the main reason why I like it." },
      { id: 'c-thesereasons', phrase: 'For these reasons, …', ko: '이런 이유로, …', slot: '이유 두 개 뒤 의견을 다시 말할 때 (11번)',
        say: 'For these reasons, I prefer living in the city.', key: 'for these reasons',
        ask: 'Do you prefer living in the city or the countryside?', example: 'There are more jobs and better transportation. For these reasons, I prefer living in the city.' },
    ],
  },
  // 유형별 표현 — type 으로 어느 유형인지 표시. 순서가 곧 우선순위(5–7은 ①~③부터)
  'q57-freq': {
    type: 'q57', name: '빈도', about: 'How often 질문에 답할 때',
    items: [
      { id: 'q57-usually', phrase: 'I usually … about once a week.', ko: '저는 보통 일주일에 한 번쯤 …해요.', slot: '답 — How often 질문',
        say: 'I usually go to the gym about once a week.', key: 'i usually',
        ask: 'How often do you go to a movie theater, and who do you go with?', example: 'I usually go to the movies about once a month with my sister.' },
      { id: 'q57-everyday', phrase: 'I … almost every day.', ko: '거의 매일 …해요.', slot: '자주 하는 일을 말할 때',
        say: 'I take the subway almost every day.', key: 'almost every day',
        ask: 'How often do you use public transportation?', example: 'I take the subway almost every day to get to work.' },
      { id: 'q57-inawhile', phrase: "I haven't … in a while.", ko: '한동안 …안 했어요.', slot: '요즘 안 하는 일을 말할 때',
        say: "I haven't been to a concert in a while.", key: 'in a while',
        ask: 'How often do you go to concerts?', example: "Honestly, I haven't been to a concert in a while. I've been really busy." },
    ],
  },
  'q57-pref': {
    type: 'q57', name: '선호', about: 'A or B, favorite 질문에 답할 때',
    items: [
      { id: 'q57-prefer', phrase: 'Personally, I prefer …', ko: '개인적으로 저는 …가 더 좋아요.', slot: '답 — A or B 질문',
        say: 'Personally, I prefer reading the news on my phone.', key: 'i prefer',
        ask: 'Do you prefer to read the news on paper or on your phone?', example: 'Personally, I prefer reading the news on my phone because I can do it anywhere.' },
      { id: 'q57-favorite', phrase: 'My favorite … is …', ko: '제가 제일 좋아하는 …는 …예요.', slot: 'favorite 질문',
        say: 'My favorite place to relax is a park near my home.', key: 'my favorite',
        ask: 'What is your favorite place to relax?', example: "My favorite place to relax is a park near my home. It's quiet and green." },
      { id: 'q57-rather', phrase: "I'd rather … than …", ko: '…보다 …하는 게 나아요.', slot: '둘 중 하나를 고를 때',
        say: "I'd rather stay home than go out on weekends.", key: "i'd rather",
        ask: 'Do you like to go out or stay home on weekends?', example: "I'd rather stay home than go out on weekends, because I need some rest." },
    ],
  },
  'q57-why': {
    type: 'q57', name: '이유', about: '답 바로 뒤에 붙이기',
    items: [
      { id: 'q57-reason', phrase: 'The main reason is that …', ko: '가장 큰 이유는 …', slot: '이유',
        say: "The main reason is that it's close to my home.", key: 'the main reason is',
        ask: 'Where do you usually buy groceries, and why?', example: "I usually buy groceries at a supermarket near my apartment. The main reason is that it's close to my home." },
      { id: 'q57-because', phrase: "It's because …", ko: '…이기 때문이에요.', slot: '이유를 짧게 댈 때',
        say: "It's because it's close to my office.", key: "it's because",
        ask: 'Why do you go to that gym?', example: "It's because it's close to my office, and it's not expensive." },
      { id: 'q57-helps', phrase: 'It helps me …', ko: '…하는 데 도움이 돼요.', slot: '좋은 점을 이유로 댈 때',
        say: 'It helps me relax after work.', key: 'it helps me',
        ask: 'Why do you listen to music?', example: 'I listen to music every day. It helps me relax after work.' },
    ],
  },
  'q57-would': {
    type: 'q57', name: '의향', about: 'Would you be interested in …? 질문에 답할 때',
    items: [
      { id: 'q57-interested', phrase: "I'd be interested in it because …", ko: '관심 있어요. 왜냐하면 …', slot: '하겠다고 답할 때',
        say: "I'd be interested in it because I could study there.", key: "i'd be interested",
        ask: 'Would you be interested in taking a cooking class?', example: "Yes, I'd be interested in it because I want to cook healthy food at home." },
      { id: 'q57-wouldnt', phrase: "I don't think I would …", ko: '저는 안 할 것 같아요.', slot: '안 하겠다고 답할 때',
        say: "I don't think I would use it, because I prefer studying at home.", key: "i don't think i would",
        ask: 'Would you use a study room at a coffee shop?', example: "I don't think I would use it, because coffee shops are too noisy for me." },
      { id: 'q57-depends', phrase: 'It depends on …', ko: '…에 따라 달라요.', slot: '조건을 달고 답할 때',
        say: 'It depends on the price.', key: 'it depends on',
        ask: 'Would you buy a new phone this year?', example: "It depends on the price. If it's not too expensive, I would buy one." },
    ],
  },
  'q57-last': {
    type: 'q57', name: '지난 경험', about: 'When was the last time …? 질문에 답할 때',
    items: [
      { id: 'q57-lasttime', phrase: 'The last time I … was …', ko: '마지막으로 …한 건 …였어요.', slot: '언제였는지 답할 때',
        say: 'The last time I went to a movie theater was two weeks ago.', key: 'the last time i',
        ask: 'When was the last time you went to a movie theater?', example: 'The last time I went to a movie theater was two weeks ago.' },
      { id: 'q57-wentwith', phrase: 'I went there with …', ko: '…와 같이 갔어요.', slot: '누구와 갔는지 덧붙일 때',
        say: 'I went there with my coworkers.', key: 'went there with',
        ask: 'When was the last time you went to a restaurant, and who did you go with?', example: 'I went to a restaurant last Friday. I went there with my coworkers.' },
      { id: 'q57-fun', phrase: 'It was a lot of fun because …', ko: '…해서 정말 재밌었어요.', slot: '경험에 느낌을 덧붙일 때',
        say: 'It was a lot of fun because the weather was perfect.', key: 'it was a lot of fun',
        ask: 'When was the last time you went on a picnic?', example: 'I went on a picnic last month. It was a lot of fun because the weather was perfect.' },
    ],
  },
  'q810-time': {
    type: 'q810', name: '날짜·시간·장소', about: '표에서 찾아 완전한 문장으로',
    items: [
      { id: 'q810-check', phrase: 'Let me check the schedule.', ko: '일정 확인해 볼게요.', slot: '답하기 전 첫 마디',
        say: 'Sure. Let me check the schedule.', key: 'let me check',
        given: 'Team Meeting — Monday, 3:00 p.m.',
        ask: 'What time is the team meeting on Monday?', example: 'Sure. Let me check the schedule. The team meeting starts at 3 p.m.' },
      { id: 'q810-sched', phrase: "It's scheduled for … at …", ko: '…일 …시로 잡혀 있어요.', slot: '날짜·시간 질문',
        say: "It's scheduled for Friday at 10 a.m.", key: 'scheduled for',
        given: 'Workshop — Tuesday, 2:00 p.m.',
        ask: 'When is the workshop?', example: "It's scheduled for Tuesday at 2 p.m." },
      { id: 'q810-held', phrase: 'It will be held in …', ko: '…에서 열려요.', slot: '장소 질문',
        say: 'It will be held in Room 203 on the second floor.', key: 'will be held',
        given: 'Seminar — Room 203, 2nd floor',
        ask: 'Where is the seminar?', example: 'It will be held in Room 203 on the second floor.' },
      { id: 'q810-startend', phrase: 'It starts at … and ends at …', ko: '…에 시작해서 …에 끝나요.', slot: '시간 범위 질문',
        say: 'It starts at 9 a.m. and ends at 5 p.m.', key: 'and ends at',
        given: 'Conference — 9:00 a.m. – 5:00 p.m.',
        ask: 'How long is the conference?', example: 'It starts at 9 a.m. and ends at 5 p.m.' },
    ],
  },
  'q810-fix': {
    type: 'q810', name: '정정', about: '틀린 정보를 물을 때',
    items: [
      { id: 'q810-afraid', phrase: "I'm afraid there's been a change.", ko: '죄송하지만 변경이 있었어요.', slot: '바뀐 일정을 알릴 때',
        say: "I'm afraid there's been a change. The meeting was moved to Thursday.", key: "i'm afraid",
        given: 'Lunch — 12:30 p.m. → changed to 1:00 p.m.',
        ask: 'Lunch starts at 12:30, right?', example: "I'm afraid there's been a change. Lunch now starts at 1 p.m." },
      { id: 'q810-actually', phrase: "Actually, that's not correct.", ko: '사실 그건 맞지 않아요.', slot: '틀린 정보를 바로잡을 때',
        say: "Actually, that's not correct. It's on Wednesday, not Tuesday.", key: "that's not correct",
        given: 'Staff Training — Wednesday',
        ask: 'The staff training is on Tuesday, right?', example: "Actually, that's not correct. It's on Wednesday, not Tuesday." },
      { id: 'q810-canceled', phrase: 'Unfortunately, … has been canceled.', ko: '아쉽게도 …는 취소됐어요.', slot: '취소된 일정을 물을 때',
        say: 'Unfortunately, the interview workshop has been canceled.', key: 'has been canceled',
        given: 'Workshop: Interview Skills — CANCELED',
        ask: "I'd like to attend the interview workshop. Is it still on?", example: 'Unfortunately, the interview workshop has been canceled.' },
    ],
  },
  'q810-multi': {
    type: 'q810', name: '여러 항목 설명', about: '10번 — 두 개 이상을 이어서',
    items: [
      { id: 'q810-two', phrase: 'There are two … The first one is …', ko: '…가 두 개 있어요. 첫 번째는 …', slot: '두 항목 요약',
        say: 'There are two sessions. The first one is at 9, and the second one is at 11.', key: 'there are two',
        given: '9:00 Social Media Basics / 11:00 Email Marketing',
        ask: 'Can you tell me about the sessions on marketing?', example: 'There are two sessions. The first one is Social Media Basics at 9 a.m., and the second one is Email Marketing at 11 a.m.' },
      { id: 'q810-firstafter', phrase: 'First, … After that, …', ko: '먼저 …, 그다음 …', slot: '순서대로 설명할 때',
        say: "First, there's a welcome speech. After that, there's a workshop.", key: 'after that',
        given: '9:00 Welcome Speech / 10:00 Workshop',
        ask: 'What happens in the morning?', example: "First, there's a welcome speech at 9. After that, there's a workshop at 10." },
      { id: 'q810-talk', phrase: '… will give a talk on …', ko: '…가 …에 대해 발표해요.', slot: '발표자·주제를 말할 때',
        say: 'Mr. Kim will give a talk on marketing.', key: 'will give a talk',
        given: '11:00 Talk: Online Marketing — Sarah Lee',
        ask: 'Who is speaking at 11?', example: 'Sarah Lee will give a talk on online marketing at 11 a.m.' },
    ],
  },
  'q810-cost': {
    type: 'q810', name: '가격·조건', about: '숫자는 또박또박',
    items: [
      { id: 'q810-costs', phrase: 'It costs … per person.', ko: '1인당 …예요.', slot: '가격 질문 — 15/50 구분',
        say: 'It costs 15 dollars per person.', key: 'per person',
        given: 'Fee: $15 per person',
        ask: 'How much is the fee?', example: 'It costs 15 dollars per person.' },
      { id: 'q810-provided', phrase: '… is provided.', ko: '…가 제공돼요.', slot: '포함 사항 질문',
        say: 'Lunch is provided for all participants.', key: 'is provided',
        given: 'Lunch (provided)',
        ask: 'Do I need to bring my own lunch?', example: "No, you don't. Lunch is provided for all participants." },
      { id: 'q810-advance', phrase: 'You need to … in advance.', ko: '미리 …해야 해요.', slot: '등록·예약 조건',
        say: 'You need to register in advance.', key: 'in advance',
        given: 'Registration required by May 10',
        ask: 'Can I just show up on the day?', example: "I'm afraid not. You need to register in advance, by May 10." },
    ],
  },
  'q11-opinion': {
    type: 'q11', name: '의견 밝히기', about: '첫 문장',
    items: [
      { id: 'q11-better', phrase: "I think it's better to …", ko: '…하는 게 더 낫다고 생각해요.', slot: '선택형 질문의 첫 문장',
        say: "I think it's better to work in a team.", key: "i think it's better to",
        ask: 'Is it better to work alone or in a team?', example: "I think it's better to work in a team, because we can share ideas." },
      { id: 'q11-agree', phrase: 'I agree that …', ko: '…라는 데 동의해요.', slot: '찬반 질문에 찬성할 때',
        say: 'I agree that students should have part-time jobs.', key: 'i agree that',
        ask: 'Do you agree that students should have part-time jobs?', example: 'I agree that students should have part-time jobs, because they can learn about work.' },
      { id: 'q11-disagree', phrase: 'I disagree with the idea that …', ko: '…라는 생각에 반대해요.', slot: '찬반 질문에 반대할 때',
        say: 'I disagree with the idea that online classes are better.', key: 'i disagree with',
        ask: 'Do you agree that online classes are better than classroom classes?', example: "I disagree with the idea that online classes are better. It's hard to focus at home." },
      { id: 'q11-believe', phrase: 'I strongly believe that …', ko: '…라고 확신해요.', slot: '의견을 힘 있게 말할 때',
        say: 'I strongly believe that reading is important for children.', key: 'i strongly believe',
        ask: 'Is reading important for children?', example: 'I strongly believe that reading is important for children, because it builds their imagination.' },
    ],
  },
  'q11-order': {
    type: 'q11', name: '이유 순서 잡기', about: '이유를 두세 개로 나눠 말하기',
    items: [
      { id: 'q11-firstofall', phrase: 'First of all, …', ko: '우선, …', slot: '첫 번째 이유',
        say: 'First of all, it helps you save money.', key: 'first of all',
        ask: 'Why is it good to have a part-time job?', example: 'First of all, it helps you save money for the future.' },
      { id: 'q11-second', phrase: 'The second reason is that …', ko: '두 번째 이유는 …', slot: '두 번째 이유',
        say: 'The second reason is that you can meet new people.', key: 'the second reason is',
        ask: 'Give a second reason why part-time jobs are good.', example: 'The second reason is that you can meet new people at work.' },
      { id: 'q11-mostimportant', phrase: 'Most importantly, …', ko: '무엇보다, …', slot: '가장 강한 이유를 강조할 때',
        say: "Most importantly, it's good for your health.", key: 'most importantly',
        ask: 'Why should people exercise regularly?', example: "It makes you feel better. Most importantly, it's good for your health." },
    ],
  },
  'q11-ex': {
    type: 'q11', name: '예시·경험', about: '이유 뒤에 받쳐주기 — 60초 채우는 핵심',
    items: [
      { id: 'q11-example', phrase: 'For example, when I …', ko: '예를 들어, 제가 …했을 때', slot: '이유 뒤 예시',
        say: 'For example, when I worked at a cafe, I learned a lot from my coworkers.', key: 'for example',
        ask: 'Do you think part-time jobs are useful for students?', example: 'Yes, I think so. For example, when I worked at a cafe, I learned how to talk to customers.' },
      { id: 'q11-experience', phrase: 'In my experience, …', ko: '제 경험으로는, …', slot: '경험에서 얻은 생각을 말할 때',
        say: 'In my experience, working in a team makes me more creative.', key: 'in my experience',
        ask: 'Is it better to work alone or in a team?', example: 'In my experience, working in a team makes me more creative.' },
      { id: 'q11-seen', phrase: "I've seen many people …", ko: '…하는 사람을 많이 봤어요.', slot: '주변 사례로 받쳐줄 때',
        say: "I've seen many people change jobs for a better salary.", key: "i've seen many people",
        ask: 'Is salary the most important thing when choosing a job?', example: "Not always, but I've seen many people change jobs for a better salary." },
    ],
  },
  'q11-compare': {
    type: 'q11', name: '장단점 비교', about: 'A vs B 선택형',
    items: [
      { id: 'q11-advantage', phrase: 'The biggest advantage of … is …', ko: '…의 가장 큰 장점은 …', slot: '장점을 짚을 때',
        say: 'The biggest advantage of living in a city is convenience.', key: 'the biggest advantage of',
        ask: 'Do you prefer living in a city or in the countryside?', example: 'The biggest advantage of living in a city is convenience. Everything is close.' },
      { id: 'q11-disadvantage', phrase: 'One disadvantage is that …', ko: '한 가지 단점은 …', slot: '단점을 짚을 때',
        say: 'One disadvantage is that it can be noisy.', key: 'one disadvantage is',
        ask: 'What is a downside of living in a big city?', example: 'One disadvantage is that it can be noisy at night.' },
      { id: 'q11-compared', phrase: 'Compared to …, …', ko: '…에 비해, …', slot: '두 쪽을 직접 비교할 때',
        say: 'Compared to buses, subways are faster.', key: 'compared to',
        ask: 'Which is better for commuting, buses or subways?', example: 'Compared to buses, subways are faster and more reliable.' },
    ],
  },
  'q11-close': {
    type: 'q11', name: '결론', about: '마지막 문장',
    items: [
      { id: 'q11-concl', phrase: 'In conclusion, …', ko: '결론적으로, …', slot: '결론 — 마지막 문장',
        say: 'In conclusion, I believe teamwork is more effective.', key: 'in conclusion',
        ask: 'Should companies let employees work from home?', example: 'In conclusion, I believe working from home is good for both companies and employees.' },
      { id: 'q11-sumup', phrase: 'To sum up, …', ko: '정리하면, …', slot: '이유들을 모아 결론낼 때',
        say: 'To sum up, I believe part-time jobs are good for students.', key: 'to sum up',
        ask: 'Should students have part-time jobs? Give a short conclusion.', example: 'To sum up, I believe part-time jobs are good for students.' },
      { id: 'q11-choose', phrase: 'So, I would choose …', ko: '그래서 저는 …를 고르겠어요.', slot: '선택형 질문의 마지막 문장',
        say: 'So, I would choose to work in a team.', key: 'i would choose',
        ask: 'Would you rather work alone or in a team?', example: 'Working together is fun and creative. So, I would choose to work in a team.' },
    ],
  },
};

if (typeof module !== 'undefined') module.exports = { EXPR };
